name       : qt6-gamepad
version    : 6.3.0
release    : 4
source     :
    - git|https://github.com/qt/qtgamepad : 41732a6ae4d3d9702e3a2e3c2f3b25ee2fe67c1c
license    :
    - GFDL-1.3-or-later
    - GPL-3.0-or-later
    - LGPL-3.0-or-later
component  :
    - desktop.qt
    - demos : programming.library
summary    : Qt6 Gamepad module
description: |
    A Qt6 module that adds support for getting events from gamepad devices on multiple platforms.
builddeps  :
    - pkgconfig(Qt6Core)
    - pkgconfig(libevdev)
    - pkgconfig(sdl2)
rundeps    :
    - devel :
        - libevdev-devel
        - qt6-base-devel
        - sdl2-devel
setup      : |
    qmake6 \
        QMAKE_CFLAGS_RELEASE="${CFLAGS}" \
        QMAKE_CXXFLAGS_RELEASE="${CXXFLAGS}" \
        QMAKE_LFLAGS="${LDFLAGS}" \
        CONFIG+=release \
        qtgamepad.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
    rm -rf $installdir/usr/lib*/pkgconfig
patterns   :
    - devel :
        - /usr/lib64/qt6/mkspecs
    - demos :
        - /usr/lib64/qt6/examples
